version: '3.8'
services:
  meet_recorder:
    build: ./google_recorder
    container_name: meet_recorder
    env_file: ./google_recorder/.env
    environment:
      POSTGRES_HOST: db-postgresql-fra1-80115-do-user-18199429-0.d.db.ondigitalocean.com
      CHROME_BIN: /usr/bin/google-chrome-stable
      CHROMEDRIVER_PATH: /usr/bin/chromedriver
    expose:
      - '8001'
    networks:
      - vct_network
    volumes:
      - ./recordings_data:/home/pulse/app/recordings

  backend:
    build:
      context: ./backend
    container_name: vct_backend
    env_file:
      - .env
    expose:
      - '8000'
    volumes:
      - ./recordings_data:/recordings
    networks:
      - vct_network
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
    container_name: vct_frontend
    env_file:
      - .env
    depends_on:
      - backend
    expose:
      - '80'
    networks:
      - vct_network

networks:
  vct_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
